import type { Concept, ContentPack } from "./types";

const concepts: readonly Concept[] = [
  {
    id: "dog",
    source: { uk: "собака" },
    target: { en: "dog" },
    glyph: "🐕",
    category: "animals",
    difficulty: 1,
    distractorIds: ["cat", "horse", "cow", "pig", "bird"],
    reviewStatus: "prototype",
  },
  {
    id: "cat",
    source: { uk: "кіт" },
    target: { en: "cat" },
    glyph: "🐈",
    category: "animals",
    difficulty: 1,
    distractorIds: ["dog", "horse", "cow", "pig", "bird"],
    reviewStatus: "prototype",
  },
  {
    id: "horse",
    source: { uk: "кінь" },
    target: { en: "horse" },
    glyph: "🐎",
    category: "animals",
    difficulty: 1,
    distractorIds: ["dog", "cat", "cow", "pig", "bird"],
    reviewStatus: "prototype",
  },
  {
    id: "cow",
    source: { uk: "корова" },
    target: { en: "cow" },
    glyph: "🐄",
    category: "animals",
    difficulty: 1,
    distractorIds: ["dog", "cat", "horse", "pig", "bird"],
    reviewStatus: "prototype",
  },
  {
    id: "pig",
    source: { uk: "свиня" },
    target: { en: "pig" },
    glyph: "🐖",
    category: "animals",
    difficulty: 1,
    distractorIds: ["dog", "cat", "horse", "cow", "bird"],
    reviewStatus: "prototype",
  },
  {
    id: "bird",
    source: { uk: "птах" },
    target: { en: "bird" },
    glyph: "🐦",
    category: "animals",
    difficulty: 1,
    distractorIds: ["dog", "cat", "horse", "cow", "pig"],
    reviewStatus: "prototype",
  },
  {
    id: "apple",
    source: { uk: "яблуко" },
    target: { en: "apple" },
    glyph: "🍎",
    category: "food",
    difficulty: 1,
    distractorIds: ["bread", "milk", "cheese", "egg", "water"],
    reviewStatus: "prototype",
  },
  {
    id: "bread",
    source: { uk: "хліб" },
    target: { en: "bread" },
    glyph: "🍞",
    category: "food",
    difficulty: 1,
    distractorIds: ["apple", "milk", "cheese", "egg", "water"],
    reviewStatus: "prototype",
  },
  {
    id: "milk",
    source: { uk: "молоко" },
    target: { en: "milk" },
    glyph: "🥛",
    category: "food",
    difficulty: 1,
    distractorIds: ["apple", "bread", "cheese", "egg", "water"],
    reviewStatus: "prototype",
  },
  {
    id: "cheese",
    source: { uk: "сир" },
    target: { en: "cheese" },
    glyph: "🧀",
    category: "food",
    difficulty: 1,
    distractorIds: ["apple", "bread", "milk", "egg", "water"],
    reviewStatus: "prototype",
  },
  {
    id: "egg",
    source: { uk: "яйце" },
    target: { en: "egg" },
    glyph: "🥚",
    category: "food",
    difficulty: 1,
    distractorIds: ["apple", "bread", "milk", "cheese", "water"],
    reviewStatus: "prototype",
  },
  {
    id: "water",
    source: { uk: "вода" },
    target: { en: "water" },
    glyph: "💧",
    category: "food",
    difficulty: 1,
    distractorIds: ["apple", "bread", "milk", "cheese", "egg"],
    reviewStatus: "prototype",
  },
  {
    id: "car",
    source: { uk: "автомобіль" },
    target: { en: "car" },
    glyph: "🚗",
    category: "transport",
    difficulty: 1,
    distractorIds: ["bus", "train", "plane", "boat", "bicycle"],
    reviewStatus: "prototype",
  },
  {
    id: "bus",
    source: { uk: "автобус" },
    target: { en: "bus" },
    glyph: "🚌",
    category: "transport",
    difficulty: 1,
    distractorIds: ["car", "train", "plane", "boat", "bicycle"],
    reviewStatus: "prototype",
  },
  {
    id: "train",
    source: { uk: "поїзд" },
    target: { en: "train" },
    glyph: "🚆",
    category: "transport",
    difficulty: 1,
    distractorIds: ["car", "bus", "plane", "boat", "bicycle"],
    reviewStatus: "prototype",
  },
  {
    id: "plane",
    source: { uk: "літак" },
    target: { en: "plane" },
    glyph: "✈️",
    category: "transport",
    difficulty: 1,
    distractorIds: ["car", "bus", "train", "boat", "bicycle"],
    reviewStatus: "prototype",
  },
  {
    id: "boat",
    source: { uk: "човен" },
    target: { en: "boat" },
    glyph: "⛵",
    category: "transport",
    difficulty: 1,
    distractorIds: ["car", "bus", "train", "plane", "bicycle"],
    reviewStatus: "prototype",
  },
  {
    id: "bicycle",
    source: { uk: "велосипед" },
    target: { en: "bicycle" },
    glyph: "🚲",
    category: "transport",
    difficulty: 1,
    distractorIds: ["car", "bus", "train", "plane", "boat"],
    reviewStatus: "prototype",
  },
  {
    id: "sun",
    source: { uk: "сонце" },
    target: { en: "sun" },
    glyph: "☀️",
    category: "nature",
    difficulty: 1,
    distractorIds: ["moon", "tree", "flower", "river", "mountain"],
    reviewStatus: "prototype",
  },
  {
    id: "moon",
    source: { uk: "Місяць" },
    target: { en: "moon" },
    glyph: "🌙",
    category: "nature",
    difficulty: 1,
    distractorIds: ["sun", "tree", "flower", "river", "mountain"],
    reviewStatus: "prototype",
  },
  {
    id: "tree",
    source: { uk: "дерево" },
    target: { en: "tree" },
    glyph: "🌳",
    category: "nature",
    difficulty: 1,
    distractorIds: ["sun", "moon", "flower", "river", "mountain"],
    reviewStatus: "prototype",
  },
  {
    id: "flower",
    source: { uk: "квітка" },
    target: { en: "flower" },
    glyph: "🌼",
    category: "nature",
    difficulty: 1,
    distractorIds: ["sun", "moon", "tree", "river", "mountain"],
    reviewStatus: "prototype",
  },
  {
    id: "river",
    source: { uk: "річка" },
    target: { en: "river" },
    glyph: "🌊",
    category: "nature",
    difficulty: 1,
    distractorIds: ["sun", "moon", "tree", "flower", "mountain"],
    reviewStatus: "prototype",
  },
  {
    id: "mountain",
    source: { uk: "гора" },
    target: { en: "mountain" },
    glyph: "⛰️",
    category: "nature",
    difficulty: 1,
    distractorIds: ["sun", "moon", "tree", "flower", "river"],
    reviewStatus: "prototype",
  },
];

export const CONTENT_PACK: ContentPack = {
  schemaVersion: 1,
  id: "uk-en-starter",
  title: "Українська → English",
  sourceLocale: "uk",
  targetLocale: "en",
  concepts,
  lessons: [
    {
      id: "animals",
      title: "Тварини",
      subtitle: "Собака, кіт та друзі",
      glyph: "🐾",
      conceptIds: ["dog", "cat", "horse", "cow", "pig", "bird"],
    },
    {
      id: "food",
      title: "Їжа й напої",
      subtitle: "Шість знайомих слів",
      glyph: "🍎",
      conceptIds: ["apple", "bread", "milk", "cheese", "egg", "water"],
    },
    {
      id: "transport",
      title: "Транспорт",
      subtitle: "Від велосипеда до літака",
      glyph: "🚲",
      conceptIds: ["car", "bus", "train", "plane", "boat", "bicycle"],
    },
    {
      id: "nature",
      title: "Природа",
      subtitle: "Сонце, річка та гори",
      glyph: "🌿",
      conceptIds: ["sun", "moon", "tree", "flower", "river", "mountain"],
    },
  ],
};

export function conceptById(pack: ContentPack, id: string): Concept {
  const concept = pack.concepts.find((candidate) => candidate.id === id);
  if (!concept) {
    throw new Error(`Unknown concept: ${id}`);
  }
  return concept;
}
